/*{"k":"0.11.0","mac":"1:23fd046ca42eeeecc5a1c2e1e69abd79023c9c194bde15f1abed270128bbe3ee","version":"9847664","created":"2012-02-26T05:33:34Z"}*/
;(function(window,document,undefined){
var j=true,o=null,q=false;function r(a){return function(c){this[a]=c}}function s(a){return function(){return this[a]}}var t;function u(a,c){var b=arguments.length>2?Array.prototype.slice.call(arguments,2):[];return function(){b.push.apply(b,arguments);return c.apply(a,b)}}function v(a,c){this.p=a;this.j=c}t=v.prototype;
t.createElement=function(a,c,b){a=this.p.createElement(a);if(c)for(var d in c)if(c.hasOwnProperty(d))if(d=="style"){var e=a,g=c[d];if(this.j.getName()=="MSIE")e.style.cssText=g;else e.setAttribute("style",g)}else a.setAttribute(d,c[d]);b&&a.appendChild(this.p.createTextNode(b));return a};t.insertInto=function(a,c){var b=this.p.getElementsByTagName(a)[0];if(!b)b=document.documentElement;if(b&&b.lastChild){b.insertBefore(c,b.lastChild);return j}return q};
t.whenBodyExists=function(a){function c(){document.body?a():setTimeout(c,0)}c()};t.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return j}return q};t.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};t.appendClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")};
t.removeClassName=function(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,g=b.length;e<g;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};t.hasClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return j;return q};function w(a,c,b,d,e,g,k,h){this.S=a;this.Sa=c;this.Ba=b;this.Aa=d;this.Ma=e;this.La=g;this.za=k;this.Wa=h}t=w.prototype;t.getName=s("S");t.getVersion=s("Sa");t.getEngine=s("Ba");t.getEngineVersion=s("Aa");
t.getPlatform=s("Ma");t.getPlatformVersion=s("La");t.getDocumentMode=s("za");function x(a,c){this.j=a;this.v=c}var aa=new w("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,q);
x.prototype.parse=function(){var a;if(this.j.indexOf("MSIE")!=-1){a=y(this,this.j,/(MSIE [\d\w\.]+)/,1);if(a!=""){var c=a.split(" ");a=c[0];c=c[1];a=new w(a,c,a,c,z(this),A(this),B(this,this.v),C(this,c)>=6)}else a=new w("MSIE","Unknown","MSIE","Unknown",z(this),A(this),B(this,this.v),q)}else{if(this.j.indexOf("Opera")!=-1)a:{c=a="Unknown";var b=y(this,this.j,/(Presto\/[\d\w\.]+)/,1);if(b!=""){c=b.split("/");a=c[0];c=c[1]}else{if(this.j.indexOf("Gecko")!=-1)a="Gecko";b=y(this,this.j,/rv:([^\)]+)/,
1);if(b!="")c=b}if(this.j.indexOf("Version/")!=-1){b=y(this,this.j,/Version\/([\d\.]+)/,1);if(b!=""){a=new w("Opera",b,a,c,z(this),A(this),B(this,this.v),C(this,b)>=10);break a}}b=y(this,this.j,/Opera[\/ ]([\d\.]+)/,1);a=b!=""?new w("Opera",b,a,c,z(this),A(this),B(this,this.v),C(this,b)>=10):new w("Opera","Unknown",a,c,z(this),A(this),B(this,this.v),q)}else{if(this.j.indexOf("AppleWebKit")!=-1){a=z(this);c=A(this);b=y(this,this.j,/AppleWebKit\/([\d\.]+)/,1);if(b=="")b="Unknown";var d="Unknown";
if(this.j.indexOf("Chrome")!=-1||this.j.indexOf("CrMo")!=-1)d="Chrome";else if(this.j.indexOf("Safari")!=-1)d="Safari";else if(this.j.indexOf("AdobeAIR")!=-1)d="AdobeAIR";var e="Unknown";if(this.j.indexOf("Version/")!=-1)e=y(this,this.j,/Version\/([\d\.\w]+)/,1);else if(d=="Chrome")e=y(this,this.j,/(Chrome|CrMo)\/([\d\.]+)/,2);else if(d=="AdobeAIR")e=y(this,this.j,/AdobeAIR\/([\d\.]+)/,1);var g=q;if(d=="AdobeAIR"){g=y(this,e,/\d+\.(\d+)/,1);g=C(this,e)>2||C(this,e)==2&&parseInt(g,10)>=5}else{g=y(this,
b,/\d+\.(\d+)/,1);g=C(this,b)>=526||C(this,b)>=525&&parseInt(g,10)>=13}a=new w(d,e,"AppleWebKit",b,a,c,B(this,this.v),g)}else{if(this.j.indexOf("Gecko")!=-1){c=a="Unknown";d=q;if(this.j.indexOf("Firefox")!=-1){a="Firefox";b=y(this,this.j,/Firefox\/([\d\w\.]+)/,1);if(b!=""){d=y(this,b,/\d+\.(\d+)/,1);c=b;d=b!=""&&C(this,b)>=3&&parseInt(d,10)>=5}}else if(this.j.indexOf("Mozilla")!=-1)a="Mozilla";b=y(this,this.j,/rv:([^\)]+)/,1);if(b=="")b="Unknown";else if(!d){d=C(this,b);e=parseInt(y(this,b,/\d+\.(\d+)/,
1),10);g=parseInt(y(this,b,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&e>9||d==1&&e==9&&g>=2||b.match(/1\.9\.1b[123]/)!=o||b.match(/1\.9\.1\.[\d\.]+/)!=o}a=new w(a,c,"Gecko",b,z(this),A(this),B(this,this.v),d)}else a=aa;a=a}a=a}a=a}return a};function z(a){var c=y(a,a.j,/(iPod|iPad|iPhone|Android)/,1);if(c!="")return c;a=y(a,a.j,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function A(a){var c=y(a,a.j,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(c)return c;if(c=y(a,a.j,/(iPhone )?OS ([\d_]+)/,2))return c;if(a=y(a,a.j,/Linux ([i\d]+)/,1))return a;return"Unknown"}function C(a,c){var b=y(a,c,/(\d+)/,1);if(b!="")return parseInt(b,10);return-1}function y(a,c,b,d){if((a=c.match(b))&&a[d])return a[d];return""}function B(a,c){if(c.documentMode)return c.documentMode}function ba(a,c,b,d){this.c=a;this.l=c;this.V=b;this.o=d||"wf";this.m=new D("-")}
function E(a){a.c.removeClassName(a.l,a.m.k(a.o,"loading"));a.c.hasClassName(a.l,a.m.k(a.o,"active"))||a.c.appendClassName(a.l,a.m.k(a.o,"inactive"));G(a,"inactive")}function G(a,c,b,d){a.V[c]&&a.V[c](b,d)}function H(a,c,b,d,e){this.c=a;this.C=c;this.F=b;this.t=d;this.K=e;this.Y=0;this.ta=this.ga=q}
H.prototype.watch=function(a,c,b,d,e){for(var g=a.length,k=0;k<g;k++){var h=a[k];c[h]||(c[h]=["n4"]);this.Y+=c[h].length}if(e)this.ga=e;for(k=0;k<g;k++){h=a[k];e=c[h];for(var f=b[h],l=0,n=e.length;l<n;l++){var p=e[l],i=this.C,m=h,F=p;i.c.appendClassName(i.l,i.m.k(i.o,m,F,"loading"));G(i,"fontloading",m,F);i=u(this,this.Ca);m=u(this,this.Da);(new d(i,m,this.c,this.F,this.t,this.K,h,p,f)).start()}}};
H.prototype.Ca=function(a,c){var b=this.C;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.removeClassName(b.l,b.m.k(b.o,a,c,"inactive"));b.c.appendClassName(b.l,b.m.k(b.o,a,c,"active"));G(b,"fontactive",a,c);this.ta=j;I(this)};H.prototype.Da=function(a,c){var b=this.C;b.c.removeClassName(b.l,b.m.k(b.o,a,c,"loading"));b.c.hasClassName(b.l,b.m.k(b.o,a,c,"active"))||b.c.appendClassName(b.l,b.m.k(b.o,a,c,"inactive"));G(b,"fontinactive",a,c);I(this)};
function I(a){if(--a.Y==0&&a.ga)if(a.ta){a=a.C;a.c.removeClassName(a.l,a.m.k(a.o,"loading"));a.c.removeClassName(a.l,a.m.k(a.o,"inactive"));a.c.appendClassName(a.l,a.m.k(a.o,"active"));G(a,"active")}else E(a.C)}
function J(a,c,b,d,e,g,k,h,f){this.va=a;this.Ga=c;this.c=b;this.F=d;this.t=e;this.K=g;this.Ka=new ca;this.Fa=new da;this.ba=k;this.aa=h;this.Ea=f||"BESbswy";this.ia=ea(this,"arial,'URW Gothic L',sans-serif");this.ja=ea(this,"Georgia,'Century Schoolbook L',serif");this.ea=this.ia;this.fa=this.ja;this.oa=K(this,"arial,'URW Gothic L',sans-serif");this.pa=K(this,"Georgia,'Century Schoolbook L',serif")}J.prototype.start=function(){this.Qa=this.K();this.W()};
J.prototype.W=function(){var a=this.F.P(this.oa),c=this.F.P(this.pa);if((this.ia!=a||this.ja!=c)&&this.ea==a&&this.fa==c)fa(this,this.va);else if(this.K()-this.Qa>=5E3)fa(this,this.Ga);else{this.ea=a;this.fa=c;ga(this)}};function ga(a){a.t(function(c,b){return function(){b.call(c)}}(a,a.W),25)}function fa(a,c){a.c.removeElement(a.oa);a.c.removeElement(a.pa);c(a.ba,a.aa)}function ea(a,c){var b=K(a,c,j),d=a.F.P(b);a.c.removeElement(b);return d}
function K(a,c,b){c=a.c.createElement("span",{style:ha(a,c,a.aa,b)},a.Ea);a.c.insertInto("body",c);return c}function ha(a,c,b,d){b=a.Fa.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(d?"":a.Ka.quote(a.ba)+",")+c+";"+b}function D(a){this.Ia=a||"-"}D.prototype.k=function(){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.Ia)};
function ca(){this.na="'"}ca.prototype.quote=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");d.indexOf(" ")==-1?c.push(d):c.push(this.na+d+this.na)}return c.join(",")};function da(){this.la=ia;this.G=ja}var ia=["font-style","font-weight"],ja={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function ka(a,c,b){this.Ha=a;this.Na=c;this.G=b}ka.prototype.expand=function(a,c){for(var b=0;b<this.G.length;b++)if(c==this.G[b][0]){a[this.Ha]=this.Na+":"+this.G[b][1];break}};da.prototype.expand=function(a){if(a.length!=2)return o;for(var c=[o,o],b=0,d=this.la.length;b<d;b++){var e=this.la[b];(new ka(b,e,this.G[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":o};function L(a,c){this.p=a;this.j=c}L.prototype=v.prototype;
L.prototype.isHttps=function(){return this.p.location.protocol=="https:"};L.prototype.getHostName=function(){return this.p.location.hostname};L.prototype.loadScript=function(a,c){var b=this.p.getElementsByTagName("head")[0];if(b){var d=this.p.createElement("script");d.src=a;var e=q;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){e=j;c&&c();d.onload=d.onreadystatechange=o;d.parentNode.tagName=="HEAD"&&b.removeChild(d)}};b.appendChild(d)}};
L.prototype.createStyle=function(a){var c=this.p.createElement("style");c.setAttribute("type","text/css");if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));return c};function la(a,c){this.Oa=a;this.Z=c}function ma(a){for(var c=a.Oa.join(","),b=[],d=0;d<a.Z.length;d++){var e=a.Z[d];b.push(e.name+":"+e.value+";")}return c+"{"+b.join("")+"}"}function M(a,c,b,d){this.D=a;this.J=c;this.w=b;this.Va=d;this.ca={};this.$={}}
M.prototype.z=function(a){return a?(this.ca[a.getStylesheetFormatId()]||this.J).slice(0):this.J.slice(0)};M.prototype.getId=s("w");function na(a,c,b){for(var d=[],e=a.D.split(",")[0].replace(/"|'/g,""),g=a.z(),k,h=[],f={},l=0;l<g.length;l++){k=g[l];if(k.length>0&&!f[k]){f[k]=j;h.push(k)}}b=b.ma?b.ma(e,h,d):h;c=c.getStylesheetFormatId();a.ca[c]=b;a.$[c]=d}M.prototype.watch=function(a,c,b){var d=[],e={};oa(this,c,d,e);a(d,e,b)};
function oa(a,c,b,d){b.push(a.D);d[a.D]=a.z(c);a=a.$[c.getStylesheetFormatId()]||[];for(c=0;c<a.length;c++){for(var e=a[c],g=e.D,k=q,h=0;h<b.length;h++)if(b[h]==g)k=j;if(!k){b.push(g);d[g]=e.z()}}}function pa(a,c){this.D=a;this.J=c}pa.prototype.z=s("J");function N(a,c,b){this.Pa=a;this.Q=c;this.qa=b}N.prototype.buildUrl=function(a,c){var b=this.Pa&&a?"https:":"http:",d=typeof this.Q=="function"?this.Q(b):this.Q;return b+"//"+d+(this.qa=="/"?"":this.qa)+c};
function qa(a,c){var b=new Image(1,1);b.src=c;b.onload=function(){b.onload=o}}function O(a,c,b){this.w=a;this.sa=c;this.da=b}O.prototype.getId=s("w");O.prototype.getStylesheetFormatId=s("sa");O.prototype.isUserAgent=function(a){return this.da?this.da(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):q};O.prototype.buildCssUrl=function(a,c,b,d){b="/"+b+"-"+this.sa+".css";if(d)b+="?"+d;return c.buildUrl(a,b)};
function P(){this.u=[]}P.prototype.addBrowser=function(a){this.getBrowserById(a.getId())||this.u.push(a)};P.prototype.getBrowserById=function(a){for(var c=0;c<this.u.length;c++){var b=this.u[c];if(a===b.getId())return b}return o};P.prototype.findBrowser=function(a){for(var c=0;c<this.u.length;c++){var b=this.u[c];if(b.isUserAgent(a))return b}return o};P.prototype.addBrowsersToBrowserSet=function(a){for(var c=0;c<this.u.length;c++)a.addBrowser(this.u[c])};
function ra(a){this.w=a;this.M=new P;this.n=[];this.N=[];this.O=this.X=this.B=o}t=ra.prototype;t.getId=s("w");t.setSecurityToken=r("ra");t.setNestedUrl=r("ha");t.setFontFilterSet=r("O");t.setKitOptions=r("R");t.addBrowser=function(a){this.M.addBrowser(a)};t.addFontFamily=function(a){this.n.push(a)};t.addCssRule=function(a){this.N.push(a)};t.supportsBrowser=function(a){return!!this.M.getBrowserById(a.getId())};t.addBrowsersToBrowserSet=function(a){this.M.addBrowsersToBrowserSet(a)};
t.init=function(a){for(var c=[],b=0;b<this.N.length;b++)c.push(ma(this.N[b]));a.insertInto("head",a.createStyle(c.join("")))};
t.load=function(a,c,b,d){if(this.O)for(var e=sa(this.O,b.getStylesheetFormatId()),g=0;g<this.n.length;g++)na(this.n[g],b,e);if(this.B&&this.X){this.B.wa(new ta(b.getStylesheetFormatId()));g=new ua(a,this.H,this.n);e=va(this.X,b.getStylesheetFormatId(),g);for(g=0;g<e.length;g++)this.B.wa(e[g]);this.B.Ua(this.ra);g=this.B.buildUrl(a.isHttps(),this.ha)}else g=b.buildCssUrl(a.isHttps(),this.ha,this.w,this.ra);a.insertInto("head",a.createCssLink(g));c&&a.whenBodyExists(function(k,h,f,l){return function(){for(var n=
0;n<k.n.length;n++)k.n[n].watch(h,f,l&&n==k.n.length-1)}}(this,c,b,d))};t.collectFontFamilies=function(a,c,b){for(var d=0;d<this.n.length;d++)oa(this.n[d],a,c,b)};t.performOptionalActions=function(a,c,b){this.R&&b.whenBodyExists(function(d,e,g,k){return function(){var h=d.R;h.ka&&qa(h,h.ka.buildUrl(k.isHttps()));var f=d.R;h=d.w;if(f.U){f=f.U.k(h,g,k);f.setAttribute("id","typekit-badge-"+h);k.insertInto("body",f)}}}(this,a,c,b))};
function Q(a,c,b,d,e){this.Ja=a;this.c=c;this.j=b;this.l=d;this.t=e;this.q=[]}Q.prototype.L=function(a){this.q.push(a)};Q.prototype.load=function(a,c){var b=a,d=c||{};if(typeof b=="string")b=[b];else if(b&&b.length)b=b;else{d=b||{};b=[]}if(b.length)for(var e=this,g=b.length,k=0;k<b.length;k++)this.ua(b[k],function(){--g==0&&e.T(d)});else this.T(d)};Q.prototype.ua=function(a,c){this.c.loadScript(this.Ja.buildUrl(this.c.isHttps(),"/"+a+".js"),c)};
Q.prototype.T=function(a){if(a.userAgent)this.j=(new x(a.userAgent,document)).parse();a=new ba(this.c,this.l,a);for(var c=new P,b=0;b<this.q.length;b++)this.q[b].addBrowsersToBrowserSet(c);c=c.findBrowser(this.j);for(b=0;b<this.q.length;b++)this.q[b].init(this.c);if(c){a.c.appendClassName(a.l,a.m.k(a.o,"loading"));G(a,"loading");wa(this,c,a)}else E(a);this.q=[]};
function wa(a,c,b){function d(k,h,f){e.watch(k,h,{},J,f)}var e=new H(a.c,b,{P:function(k){return k.offsetWidth}},a.t,function(){return+new Date});for(b=0;b<a.q.length;b++){var g=a.q[b];if(g.supportsBrowser(c)){g.load(a.c,d,c,b==a.q.length-1);g.performOptionalActions(window,a.j,a.c)}}}function R(a,c,b){this.A=a;this.c=c;this.t=b;this.q=[]}R.prototype.L=function(a){this.q.push(a)};
R.prototype.load=function(){var a=this.A.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],d=a[b.getId()];if(d){var e=this.c,g=this.t;d(function(k,h,f){var l=new P;b.addBrowsersToBrowserSet(l);h=[];var n={};if(l=l.findBrowser(k)){b.init(e);b.load(e,o,l,g);b.collectFontFamilies(l,h,n);b.performOptionalActions(window,k,e,g)}f(!!l,h,n)})}}};function S(a,c){this.S=a;this.ma=c}S.prototype.getName=s("S");
function T(a,c){for(var b=0;b<a.I.length;b++){var d=a.I[b];if(c===d.getName())return d}return o}function sa(a,c){var b=a.r[c];return b?T(a,b):o}function va(a,c,b){var d=[];a=a.s[c]||[];for(c=0;c<a.length;c++){var e;a:switch(a[c]){case "observeddomain":e=new xa(b.c);break a;case "fontmask":e=new ya(b.H,b.n);break a;default:e=o}e&&d.push(e)}return d}function ua(a,c,b){this.c=a;this.H=c;this.n=b}function ta(a){this.Ra=a}ta.prototype.toString=s("Ra");function xa(a){this.c=a}
xa.prototype.toString=function(){var a;a=this.c.getHostName?this.c.getHostName():document.location.hostname;return encodeURIComponent(a)};function ya(a,c){this.H=a;this.n=c}ya.prototype.toString=function(){for(var a=[],c=0;c<this.n.length;c++){var b=this.n[c],d=b.z();b=b.z(this.H);for(var e=0;e<d.length;e++){var g;a:{for(g=0;g<b.length;g++)if(d[e]===b[g]){g=j;break a}g=q}a.push(g?1:0)}}a=a.join("");a=a.replace(/^0+/,"");c=[];for(d=a.length;d>0;d-=4){b=a.slice(d-4<0?0:d-4,d);c.unshift(parseInt(b,2).toString(16))}return c.join("")};
function za(a,c,b,d){this.A=a;this.p=c;this.xa=b;this.ya=d}
za.prototype.k=function(a,c,b){var d=this.p.createElement("img");d.setAttribute("width",62);d.setAttribute("height",25);d.setAttribute("src",this.xa.buildUrl(b.isHttps(),"/default.gif"));d.setAttribute("class","typekit-badge");d.setAttribute("alt","Fonts by Typekit");d.setAttribute("title","Information about the fonts used on this site");d.style.position="fixed";d.style.zIndex=2E9;d.style.right=0;d.style.bottom=0;d.style.cursor="pointer";d.style.border=0;if(c.getName()!="Opera")d.style.content="none";
d.style.display="inline";d.style["float"]="none";d.style.height="25px";d.style.left="auto";d.style.margin=0;d.style.maxHeight="25px";d.style.maxWidth="62px";d.style.minHeight="25px";d.style.minWidth="62px";d.style.orphans=2;d.style.outline="none";d.style.overflow="visible";d.style.padding=0;d.style.pageBreakAfter="auto";d.style.pageBreakBefore="auto";d.style.pageBreakInside="auto";d.style.tableLayout="auto";d.style.textIndent=0;d.style.top="auto";d.style.unicodeBidi="normal";d.style.verticalAlign=
"baseline";d.style.visibility="visible";d.style.widows=2;d.style.width="65px";var e=this.p,g=this.ya.buildUrl(q,"/"+a);U(this,d,"click",function(){e.location.href=g});if(c.getName()=="MSIE"){d.style.position="absolute";var k=this;a=function(){var h=Aa(k,"scrollLeft","scrollTop"),f=Aa(k,"clientWidth","clientHeight");d.style.bottom="auto";d.style.right="auto";d.style.top=h[1]+f[1]-25+"px";d.style.left=h[0]+f[0]-3-62+"px"};U(this,this.A,"scroll",a);U(this,this.A,"resize",a)}c=c.getPlatform();if(c=="iPhone"||
c=="iPod"||c=="iPad"||c=="Android")d.style.display="none";return d};function Aa(a,c,b){var d=0,e=0;a=a.p;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b])){d=a.documentElement[c];e=a.documentElement[b]}else if(a.body&&(a.body[c]||a.body[b])){d=a.body[c];e=a.body[b]}return[d,e]}function U(a,c,b,d){if(c.attachEvent){var e=a.A;c["e"+b+d]=d;c[b+d]=function(){c["e"+b+d](e.event)};c.attachEvent("on"+b,c[b+d])}else c.addEventListener(b,d,q)}var V=new P;
V.addBrowser(new O("safari-osx","b",function(a,c,b,d,e,g,k){var h=q;h=h||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l,n,p,i){if(f=="Safari"&&n=="AppleWebKit"||f=="Unknown"&&n=="AppleWebKit"&&(i=="iPhone"||i=="iPad"))if(f=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(f[1])>=525.13;return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("air-linux-osx-win","a",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=h||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q))||(e=="Windows"&&g=="Unknown"?j:q);if(!h)return q;return function(f,l){if(f=="AdobeAIR"){var n=/([0-9]+.[0-9]+)/.exec(l);if(n)return parseFloat(n[1])>=2.5}return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l,n,p,i,m,F){if(f=="MSIE"){if(f=/([0-9]+.[0-9]+)/.exec(l))return parseFloat(f[1])>=6&&(F===undefined||
F<9);return q}}(a,c,b,d,e,g,k)}));V.addBrowser(new O("opera-osx","b",function(a,c,b,d,e,g,k){var h=q;h=h||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k);if(!h)return q;a=a=="Opera"?parseFloat(c)>=10.54:q;return a}));
V.addBrowser(new O("safari-android2to3-ipad-iphone-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){f=/([0-9]+).([0-9]+)/.exec(m);if(i=="Android"&&f){i=parseInt(f[1]);f=parseInt(f[2]);
return i==2&&f>=2||i==3&&f<1}else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){if(i=="iPad")if(l=/^([0-9]+)_([0-9]+)/.exec(m)){f=parseInt(l[1],10);l=parseInt(l[2],10);return f>4||f==4&&l>=2}else return q;else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){if(i=="iPhone"||i=="iPod")if(l=/^([0-9]+)_([0-9]+)/.exec(m)){f=parseInt(l[1],10);l=parseInt(l[2],10);return f>4||f==4&&l>=2}else return q;else return q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l,n,p,i){if(f=="Safari"&&n=="AppleWebKit"||
f=="Unknown"&&n=="AppleWebKit"&&(i=="iPhone"||i=="iPad"))if(f=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(f[1])>=525.13;return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("ff36plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],
10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q);if(!h)return q;return function(f,l,n,p){if(n=="Gecko")if(l=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(p)){f=parseFloat(l[1]);l=parseInt(l[3],10);return f>1.9||f>=1.9&&l>1}return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("ff35-osx","b",function(a,c,b,d,e,g,k){var h=q;h=h||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l,n,p){if(n=="Gecko"){f=/1.9.1b[1-3]{1}/;return/1.9.1/.test(p)&&!f.test(p)}return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("opera-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q);if(!h)return q;a=a=="Opera"?parseFloat(c)>=10.54:q;return a}));
V.addBrowser(new O("chrome6plus-android3plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],
10);m=parseInt(f[3],10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q))||function(f,l,n,p,i,m){f=/([0-9]+).([0-9]+)/.exec(m);if(i=="Android"&&f){i=parseInt(f[1]);f=parseInt(f[2]);return i==3&&f>=1||i>3}else return q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l){if(f=="Chrome"){var n=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(l);if(n)if(parseFloat(n[1])>=6)return j}}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("safari-android3plus","f",function(a,c,b,d,e,g,k){var h=q;h=h||function(f,l,n,p,i,m){f=/([0-9]+).([0-9]+)/.exec(m);if(i=="Android"&&f){i=parseInt(f[1]);f=parseInt(f[2]);return i==3&&f>=1||i>3}else return q}(a,c,b,d,e,g,k);if(!h)return q;return function(f,l,n,p,i){if(f=="Safari"&&n=="AppleWebKit"||f=="Unknown"&&n=="AppleWebKit"&&(i=="iPhone"||i=="iPad"))if(f=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(f[1])>=525.13;return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||function(f,l,n,p,i,m){f=/^([0-9]+)(_|.)([0-9]+)/.exec(m);if(i=="Macintosh"&&f){i=parseInt(f[1],10);m=parseInt(f[3],
10);return i>10||i==10&&m>=4}else return i=="Macintosh"&&m=="Unknown"?j:q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q);if(!h)return q;return function(f,l){if(f=="Chrome"){var n=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(l);if(n){var p=parseFloat(n[1]),i=parseInt(n[2],10);n=parseInt(n[3],10);if(p>=6)return q;else if(p>4)return j;else if(p==4&&i>249)return j;else if(p==4&&i==249&&n>=4)return j}}return q}(a,c,b,d,e,g,k)}));
V.addBrowser(new O("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,d,e,g,k){var h=q;h=(h=(h=(h=(h=h||(e=="Windows"&&g=="5.1"?j:q))||(e=="Windows"&&g=="5.2"?j:q))||(e=="Windows"&&g=="6.0"?j:q))||function(f,l,n,p,i,m){f=/^([0-9]+).([0-9]+)/.exec(m);if(i=="Windows"&&f){i=parseInt(f[1],10);f=parseInt(f[2],10);return i>6||i==6&&f>=1}else return q}(a,c,b,d,e,g,k))||(e=="Ubuntu"||e=="Linux"?j:q);if(!h)return q;return function(f,l,n,p){if(n=="Gecko"){f=/1.9.1b[1-3]{1}/;return/1.9.1/.test(p)&&
!f.test(p)}return q}(a,c,b,d,e,g,k)}));V.addBrowser(new O("ie9plus-win7plus-winvista","d",function(a,c,b,d,e,g,k){var h=q;h=(h=h||function(l,n,p,i,m,F){l=/^([0-9]+).([0-9]+)/.exec(F);if(m=="Windows"&&l){m=parseInt(l[1],10);l=parseInt(l[2],10);return m>6||m==6&&l>=1}else return q}(a,c,b,d,e,g,k))||(e=="Windows"&&g=="6.0"?j:q);if(!h)return q;var f;if(a=="MSIE")f=k>=9;return f}));var W=new function(){this.I=[];this.r={}},Ba=new S("AllFonts",function(a,c){return c});T(W,Ba.getName())||W.I.push(Ba);
var Ca=new S("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var d=0;d<c.length;d++){var e=c[d],g=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;b.push(new pa(g,[e]))}a={};for(e=0;e<c.length;e++){b=c[e];d=b.charAt(1);(a[d]||(a[d]=[])).push(b)}b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<b.length;e++){g=b[e];for(var k=0;k<g.length;k++){var h=g[k];if(a[h]){d=d.concat(a[h]);break}}}b=d;d={};a=[];for(e=0;e<b.length;e++){g=b[e];if(!d[g]){d[g]=j;a.push(g)}}b=[];for(d=0;d<c.length;d++){e=
c[d];for(g=0;g<a.length;g++){k=a[g];k==e&&b.push(k)}}return b});T(W,Ca.getName())||W.I.push(Ca);W.r.a="AllFonts";W.r.b="AllFonts";W.r.d="AllFonts";W.r.e="AllFonts";W.r.f="AllFonts";W.r.g="AllFonts";W.r.h="AllFonts";W.r.i="DefaultFourFontsWithSingleFvdFamilies";var X=new function(){this.s={}};X.s.a=[];X.s.b=[];X.s.d=[];X.s.e=[];X.s.f=["observeddomain"];X.s.g=["observeddomain"];X.s.h=["observeddomain"];X.s.i=["observeddomain","fontmask"];
if(!window.Typekit){var Da=new N(j,"use.typekit.com","/"),Ea=(new x(navigator.userAgent,document)).parse(),Fa=new L(document,Ea),Ga=function(a,c){setTimeout(a,c)},Y=new Q(Da,Fa,Ea,document.documentElement,Ga),Z=new R(window,Fa,Ga);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.L}var Ha,Ia=o,Ja=o,Ka=o,La,$;Ha=new N(j,"use.typekit.com","/k");Ia=new N(j,"use.typekit.com","/badges");Ja=new N(j,"typekit.com","/colophons");Ka=new za(window,document,Ia,Ja);
La=new function(a,c,b){this.U=a;this.Ta=o;this.ka=b}(Ka,o,o);$=new ra("gfg0phy");$.setSecurityToken("3bb2a6e53c9684ffdc9a9aff195b2a62452a13f44e7d614e1442605d4b02e1543a373105af87b18f751da5dd2d2cb13dd805e0c4ddd66f174be40b3dd5653b6b0737179ea40d44343ccceb1ab50666c7e24f465c360c1e0bcee3d9d026");$.setNestedUrl(Ha);$.setKitOptions(La);$.addFontFamily(new M("ff-enzo-web",["n3","i3","i6","n7","i7"]));$.addFontFamily(new M("museo-sans",["n1","n3","i3","n5","n7","i7"]));
$.addCssRule(new la([".tk-ff-enzo-web"],[{name:"font-family",value:'"ff-enzo-web",sans-serif'}]));$.addCssRule(new la([".tk-museo-sans"],[{name:"font-family",value:'"museo-sans",sans-serif'}]));$.addBrowser(V.getBrowserById("air-linux-osx-win"));$.addBrowser(V.getBrowserById("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("chrome6plus-android3plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ff35-linux-win2003-win7plus-winvista-winxp"));
$.addBrowser(V.getBrowserById("ff35-osx"));$.addBrowser(V.getBrowserById("ff36plus-linux-osx-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ie6to8-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("ie9plus-win7plus-winvista"));$.addBrowser(V.getBrowserById("opera-linux-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("opera-osx"));$.addBrowser(V.getBrowserById("safari-android2to3-ipad-iphone-win2003-win7plus-winvista-winxp"));$.addBrowser(V.getBrowserById("safari-android3plus"));
$.addBrowser(V.getBrowserById("safari-osx"));$.setFontFilterSet(W);if(Z&&Z.A.__webfonttypekitmodule__){Z.L($);Z.load()}else window.Typekit.addKit($);
})(this,document);